stages:
  - secure
  - check
  - build
  - deploy
  - auto_trans
  - sync

variables:
  ESP_DOCS_ENV_IMAGE: "$CI_DOCKER_REGISTRY/esp-chip-errata:latest"
  ESP_DOCS_PATH: "$CI_PROJECT_DIR"
  DOCTGT: "esp32s3 esp32c6 esp32h2 esp32c2 esp32s2 esp32c3 esp32 esp32p4 esp32c5 esp32c61 esp32s31"
  DOCLANG: "en zh_CN"

include:
  - project: 'documentation/documentation-tools'
    ref: master
    file:
      - check-sensitive-info-in-repo/secure.yml # Scan repo for sensitive info
  - local: ci/check.yml # Check doc links, pre-commit hooks for MoS compliance, spelling errors, trailing spaces, end-of-file newlines
  - local: ci/build.yml # Build docs
  - local: ci/deploy.yml # Deploy docs and publish to CDP
  - local: ci/auto_trans.yml # Auto translate docs
  - local: ci/sync-packaging.yml # Sync chip-marking tables to esp-packaging
