repos:
-   repo: local
    hooks:
    - id: check-emos-compliance-rst
      name: check EMoS compliance for .rst files
      entry: check_docs_modules/check_rst_format.sh
      files: \.rst$
      language: system
      require_serial: true
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--config=.codespellrc]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
