.build_template:
  stage: build
  image: $ESP_DOCS_ENV_IMAGE
  tags:
    - build
  variables:
    DOCS_DIR: $CI_PROJECT_DIR/docs
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH       # Run for all changes to the default branch
  before_script:
    - |
      echo $CI_COMMIT_SHA
      echo $DOCTGT
      export CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r -m $CI_COMMIT_SHA)
      echo "The following files have been changed: $CHANGED_FILES"
    - |
      MODIFIED_DOCTGT=()

      for file in $CHANGED_FILES; do
          MATCHED_TARGETS=()

          echo "Checking file: $file"

          # 1. Check the path of changed files for exact match of targets
          for target in $DOCTGT; do
              echo "Checking if target matches in file path"
              if [[ "$file" =~ (^|[^a-zA-Z0-9])$target([^a-zA-Z0-9]|$|[-_/]) ]]; then
                  echo "Matched target in file path: $target"
                  MATCHED_TARGETS+=("$target")
              fi
          done

          # 2. If no match and the changed files are under shared folder, scan the file content for exact match of targets
          if [[ ${#MATCHED_TARGETS[@]} -eq 0 ]] && [[ "$file" == docs/*/*/shared/*.rst ]] && [[ -f "$file" ]]; then
            echo "No match found in path. Scanning content of $file"
            for target in $DOCTGT; do
                if grep -qE "(^|[^a-zA-Z0-9])$target([^a-zA-Z0-9]|$|[-_/])" "$file"; then
                    echo "Matched target in content: $target"
                    MATCHED_TARGETS+=("$target")
                fi
            done
          fi

          # 3. If still no match, and the changed files are under the docs folder, build all targets
          if [[ ${#MATCHED_TARGETS[@]} -eq 0 ]] && [[ "$file" == docs/** ]]; then
              echo "No match found in path or content. Building docs for all targets ..."
              MATCHED_TARGETS=($DOCTGT)
          fi

          # 4. If add build label, build all targets
          if [[ ",$CI_MERGE_REQUEST_LABELS," =~ ,build, ]]; then
            echo "Build label detected. Building docs for all targets ..."
            MATCHED_TARGETS=($DOCTGT)
          fi

          # 5. If commit to the default branch, build all targets
          if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
            echo "Commit is on default branch ($CI_DEFAULT_BRANCH). Building docs for all targets ..."
            MATCHED_TARGETS=($DOCTGT)
          fi

          MODIFIED_DOCTGT+=("${MATCHED_TARGETS[@]}")
      done

      MODIFIED_DOCTGT=($(printf "%s\n" "${MODIFIED_DOCTGT[@]}" | sort -u))

      export MODIFIED_DOCTGT="${MODIFIED_DOCTGT[@]}"
      echo "MODIFIED_DOCTGT=${MODIFIED_DOCTGT[@]}"
  parallel:
    matrix:
      - DOCLANG: ["en", "zh_CN"]
  retry: 2

build_errata_html:
  extends:
    - .build_template
  script:
    - cd $DOCS_DIR
    - bash ./check_lang_folder_sync.sh
    - pip install -r requirements.txt
    - echo $MODIFIED_DOCTGT
    - for tgt in $MODIFIED_DOCTGT; do build-docs --skip-reqs-check -l $DOCLANG -t $tgt; done
    - for tgt in $MODIFIED_DOCTGT; do echo "See $CI_JOB_URL/artifacts/file/docs/_build/$DOCLANG/$tgt/html/index.html"; done
  artifacts:
    when: always
    paths:
      - $DOCS_DIR/_build/*/*/html/*
      - $DOCS_DIR/_build/*/*/*.txt
    expire_in: 4 days

build_errata_pdf:
  extends:
    - .build_template
  script:
    - cd $DOCS_DIR
    - bash ./check_lang_folder_sync.sh
    - pip install -r requirements.txt
    - echo $MODIFIED_DOCTGT
    - for tgt in $MODIFIED_DOCTGT; do build-docs --skip-reqs-check -bs latex -l $DOCLANG -t $tgt; done
    - for tgt in $MODIFIED_DOCTGT; do echo "See $CI_JOB_URL/artifacts/file/docs/_build/$DOCLANG/$tgt/latex/build/esp-chip-errata-$DOCLANG-master-$tgt.pdf"; done
  artifacts:
    when: always
    paths:
      - $DOCS_DIR/_build/*/*/latex/*
      - $DOCS_DIR/_build/*/*/*.txt
    expire_in: 4 days
